FactoryBot.define do
  factory :user do
    # Required attributes based on validations
    name { "Test User" }
    username { "testuser#{rand(1000)}" }  # Random username to ensure uniqueness
    email { "testuser#{rand(1000)}@example.com" }
    password { "password123" }
    password_confirmation { "password123" }

    # Optional attributes that are generated by default
    confirmed_at { nil }
    confirmation_token { SecureRandom.urlsafe_base64 }
    remember_digest { nil }
    
    trait :with_remember_token do
      remember_token { "some_fake_token" }
      remember_digest { "some_fake_digest_value" }
    end
    
    # Associations
    # Optional associations (you can specify `campaigns`, `characters`, etc. if needed)
    after(:create) do |user|
      user.confirm_email if user.confirmation_token.nil?
    end

    # Callback to create a confirmation token if not provided
    before(:create) do |user|
      user.create_confirmation_token if user.confirmation_token.nil?
    end
  end
end
